### ISSUE TITLE
Error with example data 

### ISSUE THREAD

**Issue by Kapeel** [lfaino/LoReAn_Example#1]
Hi,
I am not able to replicate the example runs. Blow is the error I get.

```
/vol_b/LoReAn_Example/JR2$ sudo docker run -it --rm -v $PWD:/data lfaino/lorean /opt/LoReAn/code/lorean.py -t 2 --keep_tmp -a -f -d -sr readsChr.subset.fastq -lr longReadsChr8.fastq -pr subset.prot.fasta -sp JR2 -mg chr8.fasta
usage: lorean [options] reference
lorean: error: argument -m/--max_long_read: invalid int value: 'g'

/vol_b/LoReAn_Example/JR2$ sudo docker run -it --rm -v $PWD:/data lfaino/lorean /opt/LoReAn/code/lorean.py -t 2 --keep_tmp -a -f -d -sr readsChr.subset.fastq -lr longReadsChr8.fastq -pr subset.prot.fasta -sp JR2 chr8.fasta
#####LOREAN STOPS HERE. CHECK THAT THE PROTEIN AND SPECIES OPTION HAVE BOTH AN ARGUMENT. CHECK THAT THE gm_key IS IN THE FOLDER#####
```
it seems like the -mg optin is not able to read by lorean.py script. I tried removing that and still it fails. Another issue I saw was the augustus config folder in the container does not have the crispa or JR2  specie model.

Thanks
Kapeel

**Comment by lfaino** [comment]
This is not going to work.
you need to have a bash in docker and after run lorean

$ docker run -it --rm -v $PWD:/data lfaino/lorean:iprscan_rpMask createUser.py $USER $UID 
$ /opt/LoReAn/code/lorean.py -t 2 --keep_tmp -a -f -d -sr readsChr.subset.fastq -lr longReadsChr8.fastq -pr subset.prot.fasta -sp JR2 chr8.fasta

the first command wil download a new version of LoReAn

**Comment by Kapeel** [comment]
Thanks for the quick response,

I  pulled the new docker image and ran the first command
```
...
 2320774ce0a7: Pull complete 
a06b4dc01409: Pull complete 
2e38bad8c945: Pull complete 
Digest: sha256:f5b78b52195d11912972fc7ce3df6f78cf7511eecb9b102676f2cea81dcd1fa5
Status: Downloaded newer image for lfaino/lorean:iprscan_rpMask

### CREATING USER WITH NAME kap12 AND UID 1000 IN THE DOCKER IMAGE ###

#####PLEASE PLACE THE gm_key IN THE DIRECTORY WITH ALL THE OTHER FILES.#####
```

but it does not open bash in docker.  I have the gm_key in the same folder  as the input data. I did not see any container running as well. Am I missing something?
second command:

```
kap12@js-170-58:/vol_b/LoReAn_Example/Crispa$ /opt/LoReAn/code/lorean.py -h
-bash: /opt/LoReAn/code/lorean.py: No such file or directory
```

Thanks
Kapeel

**Comment by lfaino** [comment]
Dear Kapeel,
because of several problem with Docker, i made a new installation using Singularity. Would you be able to test this one?

the link for the installation instruction is:

https://github.com/lfaino/LoReAn/blob/dev/INSTALL.md

in this installation you can place the gm_key code in your home directory and name it .gm_key

let me know
Luigi

**Comment by Kapeel** [comment]
Thanks Luigi,

The singularity installation works great. I am testing it right now with the example data, eventually planning it to run on my datasets. 

Best

Kapeel

**Comment by ncgrjsmiao** [comment]
I also can not replicated the example with docker. Here is my and command and error info:

jsmiao@e9bf92665a36:/data$ lorean.py -a -rp repeats.scaffold3.bed -sr scaffold3.short_1.fastq,scaffold3.short_2.fastq  -lr scaffold3.long.fasta  -pr scaffold3.prot.fasta -sp crispa scaffold3.fasta -d -f -mg -t 12 --keep_tmp

 ### LOREAN IS CHECKING THAT GMAP IS CORRECTLY BUILD ###


###GMAP MAPPING  STARTED AT:	07:03:31 06-03	###
	###BUILD INDEX###
GMAP database existed already: /data/LoReAn_annotation/run//gmap_output/chr8.testGMAP.fasta_GMAPindex --- skipping	###MAP###
GMAP done already: /data/LoReAn_annotation/run//gmap_output/gmap.long_reads.test.sam --- skipping
 ### GMAP IS CORRECTLY BUILD ###


Traceback (most recent call last):
  File "/opt/LoReAn/code/lorean.py", line 552, in <module>
    main()
  File "/opt/LoReAn/code/lorean.py", line 137, in main
    augustus_species, err_augustus = logistic.augustus_species_func(home)
  File "/opt/LoReAn/code/dirsAndFiles.py", line 197, in augustus_species_func
    with open(list_file[0]) as bashrc:
IndexError: list index out of range

Thanks!

**Comment by alanorth** [comment]
I am also having problems with LoReAn's example _Plicaturopsis crispa_ data set running in Singularity:

```console
$ singularity exec -B /export/apps/lorean/latest/augustus-config:/opt/LoReAn/third_party/software/augustus/config \
>                  -B /export/apps/lorean/latest/RepeatMasker-Libraries:/usr/local/RepeatMasker/Libraries \
>                  -B /var/scratch/LoReAn_Example/Crispa:/var/scratch/LoReAn_Example/Crispa \
>                  /export/apps/lorean/latest/lorean.sif lorean -a \
>                  -rp /var/scratch/LoReAn_Example/Crispa/repeats.scaffold3.bed \
>                  -sr /var/scratch/LoReAn_Example/Crispa/scaffold3.short_1.fastq,/var/scratch/LoReAn_Example/Crispa/scaffold3.short_2.fastq \
>                  -lr /var/scratch/LoReAn_Example/Crispa/scaffold3.long.fasta \
>                  -pr /var/scratch/LoReAn_Example/Crispa/scaffold3.prot.fasta \
>                  -sp crispa /var/scratch/LoReAn_Example/Crispa/scaffold3.fasta \
>                  -d -f -mg -t 8 --keep_tmp
### RUNNING IN STRAND MODE AND USING ADAPTER PROVIDED ###
### LOREAN IS CHECKING THAT GMAP IS CORRECTLY BUILD ###

###GMAP MAPPING  STARTED AT:    19:45:42 16-08  ###
###BUILD INDEX###
###MAP###
 ### GMAP IS CORRECTLY BUILD ###


###MASKING THE GENOME STARTED AT:       19:45:42 16-08  ###
###STAR MAPPING  STARTED AT:    19:46:14 16-08  ###
###BUILD INDEX###
###MAP###
###SAM to BAM###
###SORTING BAM###
###TRINITY STARTS AT:   19:48:54 16-08  ###
###GMAP MAPPING  STARTED AT:    20:20:26 16-08  ###
###BUILD INDEX###
###MAP###
###PASA STARTS AT:      20:22:32 16-08  ###
###BRAKER1 (USING SHORT READS) AND EXONERATE STARTED AT:        20:25:46 16-08  ###
###RUNNING BRAKER1 ###
100%|#####################################################################################################| 6/6 [00:09<00:00,  1.59s/it]
###RUNNING DIAMOND MAKEDB###
###RUNNING DIAMOND ###
###RUNNING EXONERATE ###
100%|#################################################################################################| 176/176 [00:22<00:00,  7.93it/s]
Traceback (most recent call last):
  File "/opt/LoReAn/code/lorean.py", line 610, in <module>
    main()
  File "/opt/LoReAn/code/lorean.py", line 330, in main
    augustus_file, genemark_file = inputEvm.braker_folder_find(braker_folder)
  File "/opt/LoReAn/code/prepareEvmInputs.py", line 115, in braker_folder_find
    gff = [y for x in os.walk(location) for y in glob(os.path.join(x[0], "augustus.hints.gtf"))][0]
IndexError: list index out of range
```

The Augustus config is bind mounted into the container at runtime, and it exists:

```console
# ls -l /export/apps/lorean/latest/augustus-config
total 20
drwxr-xr-x.   2 root root 4096 Jul 13 15:09 cgp
drwxr-xr-x.   2 root root 4096 Jul 13 15:09 extrinsic
drwxr-xr-x.   2 root root 4096 Jul 13 15:09 model
drwxr-xr-x.   2 root root 4096 Jul 13 15:09 profile
drwxr-xr-x. 108 root root 4096 Jul 13 15:09 species
```

Does the user need write access there?

**Comment by JC-therea** [comment]
I was able to fix it running singularty shell of the image

```
singularity shell lorean_latest.sif
```

And then before running the example, I configured all the paths that showed errors

```
export AUGUSTUS_BIN_PATH=/opt/LoReAn/third_party/software/augustus/bin
export AUGUSTUS_SCRIPTS_PATH=/opt/LoReAn/third_party/software/augustus
export AUGUSTUS_CONFIG_PATH=/home/lorean/config
```
